import { useMemo, useState } from 'react'
import { ArrowUpRight, Filter, MapPin } from 'lucide-react'
import type { Target } from '../types'

export default function Targets({ targets }: { targets: Target[] }) {
  const [zone, setZone] = useState('ALL')
  const [selected, setSelected] = useState<Target | null>(null)
  const filtered = useMemo(() => targets.filter(t => zone==='ALL'||t.zone===zone).sort((a,b)=>b.score-a.score), [targets,zone])
  return <div className="space-y-5">
    <div><h1 className="text-xl font-semibold text-slate-900">Priority Targets</h1><p className="mt-1 text-sm text-slate-500">Ranked locations for geological review and field validation.</p></div>
    <div className="flex flex-wrap items-center gap-2"><Filter size={16} className="text-slate-400"/>{['ALL','HIGH','MEDIUM','LOW'].map(z=><button key={z} onClick={()=>setZone(z)} className={`rounded-full px-3 py-1.5 text-xs font-medium ${zone===z?'bg-slate-900 text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{z}</button>)}</div>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Target</th><th className="px-5 py-3">Exact location</th><th className="px-5 py-3">Score</th><th className="px-5 py-3">Confidence</th><th className="px-5 py-3">Zone</th><th className="px-5 py-3">Geology</th><th className="px-5 py-3">Evidence variations</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(t=><tr key={t.id} onClick={()=>setSelected(t)} className={`cursor-pointer hover:bg-slate-50 ${selected?.id===t.id?'bg-cyan-50/60':''}`}><td className="px-5 py-4"><div className="font-semibold text-slate-800">{t.code}</div><div className="text-xs text-slate-500">{t.name}</div></td><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-600"><div>{t.latitude.toFixed(5)}° N</div><div>{t.longitude.toFixed(5)}° E</div></td><td className="px-5 py-4 font-semibold">{t.score}/100</td><td className="px-5 py-4">{t.confidence}%</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${t.zone==='HIGH'?'bg-red-50 text-red-700':t.zone==='MEDIUM'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{t.zone}</span></td><td className="px-5 py-4 text-slate-600">{t.geology}</td><td className="max-w-xs px-5 py-4 text-xs leading-5 text-slate-600">{t.factors.join(' · ')}</td><td className="px-5 py-4"><span className="text-xs text-slate-500">{t.status}</span></td></tr>)}</tbody></table></div>
    {selected && <section className="rounded-xl border border-cyan-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="text-xs font-semibold uppercase tracking-wide text-cyan-700">Manganese target {selected.code}</div><h2 className="mt-1 text-lg font-semibold text-slate-900">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">{selected.latitude.toFixed(5)}° N, {selected.longitude.toFixed(5)}° E · {selected.geology}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">{selected.model_status.toUpperCase()} MODEL</span></div><div className="mt-5 grid gap-4 sm:grid-cols-4"><div><div className="text-xs text-slate-500">Mn prospectivity</div><div className="mt-1 text-xl font-semibold">{Math.round(selected.manganese_probability*100)}%</div></div><div><div className="text-xs text-slate-500">Confidence</div><div className="mt-1 text-xl font-semibold">{selected.confidence}%</div></div><div><div className="text-xs text-slate-500">Classification</div><div className="mt-1 text-sm font-semibold">{selected.classification.replace('_',' ')}</div></div><div><div className="text-xs text-slate-500">Priority</div><div className="mt-1 text-sm font-semibold">{selected.priority}</div></div></div><div className="mt-5 grid gap-4 border-t border-slate-100 pt-4 md:grid-cols-3"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">Supporting features</div><p className="mt-2 text-sm leading-6 text-slate-600">{selected.feature_summary.join(' · ')}</p></div><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">Available data</div><p className="mt-2 text-sm leading-6 text-slate-600">{selected.data_sources.join(' · ')}</p></div><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">Recommended next action</div><p className="mt-2 text-sm leading-6 text-slate-600">Field validation recommended before drilling.</p></div></div></section>}
    <div className="grid gap-4 md:grid-cols-3">{filtered.slice(0,3).map(t=><div key={t.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{t.code}</span><ArrowUpRight size={16} className="text-slate-400"/></div><h3 className="mt-2 font-semibold">{t.name}</h3><div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><MapPin size={14}/><span>{t.latitude.toFixed(5)}° N, {t.longitude.toFixed(5)}° E</span></div><p className="mt-3 text-xs leading-5 text-slate-500"><span className="font-medium text-slate-700">Variations:</span> {t.factors.join(' · ')}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{width:`${t.score}%`}}/></div></div>)}</div>
  </div>
}
